### ISSUE TITLE
Consider switching to "hyperquest" from "request".

### ISSUE THREAD

**Issue by Marak** [JavascriptBattle/javascript-battle-webworkers#101]
I see that the `request` library is being used with many default options.

I haven't looked too deeply into the code, but depending on the use-case, you may run into issues using the `request` library without explicitly setting certain options for pooling and max connections. The `hyperquest` library tends to have more sane default settings. 

see: https://github.com/substack/hyperquest

**Comment by forrestbthomas** [comment]
Oh, interesting. We will check in to that.
Thanks!
